WIP: config refactoring
sweepai/sweep pull request #258
Opened 2023-07-05 10:46 UTC by asc11cat

# Purpose

Reduce the amount of dead code, centralize config vars making self-hosted instances easier to deploy.

# Changes Made

Please provide a detailed list of the changes made in this pull request.

1. Removal of dead imports
2. Installation of chromadb & sentence-transformers deps 
3. Centralization of config variables in `sweepai/utils/config.py`

# Additional Notes

This PR will work only with modifications to the current secrets in Modals, please see `sweepai/utils/config.py` for that. It is still WIP, but it would be nice if someone could look at it early on.

2023-07-09 20:15 UTC, wwzeng1 commented on sweepai/core/vector_db.py
> +    # todo: ?
this is good, we run this to hydrate the cache on merge/push

2023-07-09 20:19 UTC, wwzeng1 commented on sweepai/utils/config.py
> +GITHUB_DEFAULT_CONFIG = os.environ.get('GITHUB_DEFAULT_CONFIG', """# Reference: https://github.com/sweepai/sweep/blob/main/sweep.yaml
This can default to none, we only want to change the branch if the user sets it

2023-07-09 20:31 UTC, wwzeng1 commented
This PR looks great, one of us will merge it to a test branch in sweep, should be done by tomorrow at the latest

2023-07-09 23:05 UTC, kevinlu1248 requested changes
Overall a lot of really nice changes. Main complaint is moving constants to config and removing some of the prefixes which would break prod for us :(. Other than that looks pretty good.

2023-07-12 17:37 UTC, asc11cat commented
I've adjusted the PR to your comments guys. TLDR:

1. Configs are now under utils/config/server.py OR utils/config/client.py files, and they don't depend on each other.
2. Config vars/envs now have hardcoded fallbacks with values you currently use in your prod env. It should work as it is(?), while still allowing configuration.
3. No chromadb/sentence-transformers deps bloat due to huggingface dead code removal

All other changes in the last commit are purely codestyle.

2023-07-13 01:01 UTC, kevinlu1248 approved these changes
Made some small fixes and merge conflicts. Merging now. Thanks for the contribution!

2023-07-13 01:02 UTC, kevinlu1248 approved these changes
Made some small fixes and merge conflicts. Merging now. Thanks for the contribution!

2023-07-13 01:02 UTC, kevinlu1248 approved these changes
Made some small fixes and merge conflicts. Merging now. Thanks for the contribution!

2023-07-13 01:02 UTC, merged